[#litellm-installing]
include::../common/generic-attributes.adoc[]
// overridden title?
ifdef::override-title[]
= {override-title}
endif::[]
ifndef::override-title[]
= Installing {ai-app-name}
endif::[]
// overridden abstract?
ifdef::override-abstract[]
{override-abstract}
endif::[]
ifndef::override-abstract[]
You can install {ai-app-name} either using *{ranchera}* or on the command line with *{helm}*.
endif::[]

// erase the flag for future overrides
:override-abstract!:
:override-title!:

:revdate: 2026-09-14
:page-revdate: {revdate}

[#litellm-installing-rancher]
== Installing with {ranchera}

Refer to link:https://documentation.suse.com/suse-ai-factory/latest/html/AI-Factory-usage/ai-factory-managing-apps.html#ai-factory-apps-install[AI application installation] for a general installation procedure.

[#litellm-installing-helm]
== Installing with {helm}


. Log in to {sappco} registry.
To prevent the password from being stored in the shell history, save it to the `appco-password.txt` file.
+
[,sh,subs="+attributes"]
----
{prompt_user}helm registry login dp.apps.rancher.io \
  --username=<APPCO-REGISTRY-USERNAME> \
  --password-stdin < appco-password.txt
----

. Log in to {sregistry}.
To prevent the password from being stored in the shell history, save it to the `registry-password.txt` file.
+
[,sh,subs="+attributes"]
----
{prompt_user}helm registry login registry.suse.com \
  --username=regcode \
  --password-stdin < registry-password.txt
----

. Create a namespace.
+
[,sh,subs="+attributes"]
----
{prompt_user}kubectl create namespace {ai-app-string} --dry-run=client -o yaml | kubectl apply -f -
----

. Create image pull secrets.
.. Create {sappco} image pull secrets.
+
[,sh,subs="+attributes"]
----
{prompt_user}kubectl create secret docker-registry application-collection \
  --docker-server=dp.apps.rancher.io \
  --docker-username=<APPCO-REGISTRY-USERNAME> \
  --docker-password="$(< appco-password.txt)" \
  -n {ai-app-string} \
    --dry-run=client -o yaml | kubectl apply -f -
----

.. Create {sregistry} image pull secrets.
+
[,sh,subs="+attributes"]
----
{prompt_user}kubectl create secret docker-registry suse-ai-registry \
  --docker-server=registry.suse.com \
  --docker-username=regcode \
  --docker-password="$(< registry-password.txt)" \
  -n {ai-app-string} \
  --dry-run=client -o yaml | kubectl apply -f -
----

. To override default installation values, list them in a `values.yaml` file.
For a complete list of {ai-app-name} chart values, refer to xref:{ai-app-string}-helm-values[].

. Install {ai-app-name}.
To keep the default installation values, omit `-f values.yaml`.
+
[source,subs="+attributes"]
----
{prompt_user}helm upgrade --install \
  {ai-app-string} oci://registry.suse.com/ai/charts/litellm \
  -n {ai-app-string} \
  -f values.yaml
----
