[#ai-factory-managing-blueprints]
include::../common/generic-attributes.adoc[]
// overridden title?
ifdef::override-title[]
= {override-title}
:revdate: 2026-01-26
:page-revdate: {revdate}
endif::[]
ifndef::override-title[]
= Managing AI blueprints using {productname}
endif::[]
// overridden abstract?
ifdef::override-abstract[]
{override-abstract}
endif::[]
ifndef::override-abstract[]
{productname} is a {ranchera} user interface extension and {kube} operator that helps you manage the entire lifecycle of AI applications and workloads. Implementing this tool simplifies the deployment, configuration and scaling of AI workloads on {kube}, providing a streamlined experience for administering cluster-based artificial intelligence services.
endif::[]

// erase the flag for future overrides
:override-abstract!:
:override-title!:

[#ai-factory-managing-blueprints-create]
== How do I create custom blueprints?

To create a custom blueprint, follow these steps:

. From the main left panel, click menu:SUSE AI Factory[Blueprints > Create].
. On the `Basic Info` screen, enter the blueprint's name, version and optionally a description. Confirm with btn:[Next].
. On the `Select Apps` screen, search for an application to add to the blueprint, click its name ans specify the version to install.
Repeat for all applications that you want to include in the blueprint.
Confirm with btn:[Next].
. On the `Configuration` screen, review and optionally update the blueprint's deployment {helm} chart. Confirm with btn:[Next].
. On the `Review & Create` screen, verify that the entered information is correct and confirm with btn:[Create].

[#ai-factory-managing-blueprints-modify]
== How do I modify blueprints?

To modify a blueprint, follow these steps:

. From the main left panel, click menu:SUSE AI Factory[Blueprints].
. From the list of existing blueprints, select the one to modify, click its three-dot menu and select btn:[Edit].
. On the `Basic Info` screen, update the version number and description. Confirm with btn:[Next].
. On the `Select Apps` screen, update the list of blueprint's applications by adding new applications or removing existing ones.
Confirm with btn:[Next].
. On the `Configuration` screen, review and optionally update the blueprint applications' {helm} charts. Confirm with btn:[Next].
. On the `Review & Create` screen, verify that the entered information is correct and confirm with btn:[Save as New Version].


[#ai-factory-managing-blueprints-install]
== How do I install blueprints?

To install a blueprint, follow these steps:

. From the main left panel, click menu:SUSE AI Factory[Blueprints].
. From the list of existing blueprints, select the one to install, specify the version to install, and click its btn:[Install] button.
. On the `Basic Info` screen, you can modify the default name and the target namespace for the workload. Confirm with btn:[Next].
. On the `Target` screen, specify the deployment type and the cluster that you want to deploy the workload to.
You can also review estimated hardware requirements for the workload. Confirm with btn:[Next].
. On the `Review` screen, verify that the entered information is correct and start the deployment with btn:[Install].
. Switch to menu:Workloads[] to verify that the workload deployment has started and watch the status of the deployment.

[#ai-factory-managing-blueprints-copy]
== How do I base a blueprint on an existing one?

To base a blueprint on an existing one, follow these steps:

. From the main left panel, click menu:SUSE AI Factory[Blueprints].
. From the list of existing blueprints, select the one to clone, specify its version, click its three-dot menu and select btn:[Copy].
. On the `Basic Info` screen, you can modify the suggested name, version and description. Confirm with btn:[Next].
. On the `Select Apps` screen, update the list of blueprint's applications by adding new applications or removing existing ones.
Confirm with btn:[Next].
. On the `Configuration` screen, review and optionally update the blueprint's deployment {helm} chart. Confirm with btn:[Next].
. On the `Review & Create` screen, verify that the entered information is correct and confirm with btn:[Create].

[#ai-factory-managing-blueprints-deprecate]
== How do I deprecate blueprints?

To deprecate a blueprint and hide it from the list of blueprints, follow these steps:

. From the main left panel, click menu:SUSE AI Factory[Blueprints].
. From the list of existing blueprints, select the one to deprecate.
. Specify the version to deprecate, click its three-dot menu and select btn:[Deprecate].
. Confirm with btn:[Deprecate].

[#ai-factory-managing-blueprints-undeprecate]
== How do I restore deprecated blueprints?

To restore a deprecated blueprint and make it appear in the list of blueprints, follow these steps:

. From the main left panel, click menu:SUSE AI Factory[Blueprints].
. A deprecated blueprint is hidden from the list of blueprints.
To make it appear again, activate the btn:[Show deprecated] check box.
. Select the blueprint to restore and specify its deprecated version.
. Click the blueprint's three-dot menu and select btn:[Undeprecate].
. Confirm with btn:[Undeprecate].

[#ai-factory-managing-blueprints-delete]
== How do I delete blueprints?

To delete a blueprint, follow these steps:

. From the main left panel, click menu:SUSE AI Factory[Blueprints].
. From the list of existing blueprints, select the one to delete and specify the version to delete.
. Click the blueprint's three-dot menu and select btn:[Delete].
Confirm with btn:[Delete].

[#ai-factory-managing-blueprints-multiple-envs]
== How do I manage environment-specific configurations with blueprints?

Consider the following use-case:
You have a {litellm} blueprint and want to install it on a development and production cluster using different configurations.
Due to reduced hardware resources on the development cluster, you need different LLM models, {ingress} values or GPU resource settings.
For clarity, the blueprints will be named `blueprint-litellm-dev` and `blueprint-litellm-prod`.
To achieve this task with {productname}, follow these steps:

. Use a prebuilt blueprint or create a custom blueprint as described in xref:ai-factory-managing-blueprints-create[].
This blueprint will be deployed in production, therefore update its name to `blueprint-litellm-prod`.
. Create a new version of the blueprint with the desired configurations as described in xref:ai-factory-managing-blueprints-modify[].
. Clone the blueprint as described in xref:ai-factory-managing-blueprints-copy[] and name it `blueprint-litellm-dev`.
. Deploy the blueprints as described in xref:ai-factory-managing-blueprints-install[]. Specify the correct version for each deployment.
.. blueprint `blueprint-litellm-prod` on the production cluster
.. blueprint `blueprint-litellm-dev` on the development cluster

[TIP]
====
If you need to apply a new version of a blueprint during future maintenance, go to menu:SUSE AI Factory[Workloads] and click the corresponding btn:[Upgrade] button.
====


