[#ai-factory-managing-blueprints]
include::../common/generic-attributes.adoc[]
// overridden title?
ifdef::override-title[]
= {override-title}
:revdate: 2026-01-26
:page-revdate: {revdate}
endif::[]
ifndef::override-title[]
= Managing AI blueprints using {productname}
endif::[]
// overridden abstract?
ifdef::override-abstract[]
{override-abstract}
endif::[]
ifndef::override-abstract[]
{productname} is a {ranchera} user interface extension and {kube} operator that helps you manage the entire lifecycle of AI applications and workloads. Implementing this tool simplifies the deployment, configuration and scaling of AI workloads on {kube}, providing a streamlined experience for administering cluster-based artificial intelligence services.
endif::[]

// erase the flag for future overrides
:override-abstract!:
:override-title!:

[#ai-factory-managing-blueprints-install]
== How do I install prebuilt blueprints?
{productname} is shipped with pre-built {suse} and {nvidia} blueprints that match specific use cases.
Each blueprint already includes the related applications, dependencies and configurations which simplifies the whole deployment process.

. From the main left panel, click menu:SUSE AI Factory[Blueprints].
. From the list of blueprints, select the one that you want to install and click its btn:[Install] button.
. On the `Basic Info` screen, you can modify the default name and the target namespace for the workload. Confirm with btn:[Next].
. On the `Target` screen, specify the deployment type and the cluster that you want to deploy the workload to.
You can also review estimated hardware requirements for the workload. Confirm with btn:[Next].
. On the `Review` screen, verify that the entered information is correct and start the deployment with btn:[Install].
. Switch to menu:Workloads[] to verify that the workload deployment has started and watch the status of the deployment.

// == How do I create custom blueprints?
// == How do I manage blueprint instances?
// == How do I delete blueprint instances?
