[#ai-factory-post-deployment]
include::../common/generic-attributes.adoc[]
// overridden title?
ifdef::override-title[]
= {override-title}
:revdate: 2026-01-26
:page-revdate: {revdate}
endif::[]
ifndef::override-title[]
= Steps after installing {productname}
endif::[]
// overridden abstract?
ifdef::override-abstract[]
{override-abstract}
endif::[]
ifndef::override-abstract[]
AI applications and blueprint images are stored across multiple network-accessible services.
After you deploy {productname}, provide the extension with access to these services.
endif::[]

// erase the flag for future overrides
:override-abstract!:
:override-title!:

[#ai-factory-sappco]
== How do I access images from {sappco}?

. Enter {sappco} secrets to the {ranchera} _local_ cluster.
.. From the main left panel, click menu:local[Storage > Secrets]
.. Click btn:[Create] in the top right and select btn:[Opaque]
.. Select the btn:[aif-operator] namespace and enter your preferred secrets name--see `<APPCO_SECRETS_NAME>` in the command-line example--to identify the secrets.
.. In the btn:[Data] tab, add key `user` with the value of your {sappco} username and `token` for your {sappco} token.
.. Confirm with btn:[Create] in the bottom right corner.

+
[TIP]
.Creating the secrets on the command line
====
[source,bash,subs="+attributes"]
----
{prompt_user}kubectl create secret generic <APPCO_SECRETS_NAME> \
  --from-literal=user=<APPCO_USERNAME> \
  --from-literal=token=<APPCO_USER_TOKEN> \
  -n aif-operator
----
====
. Assign {sappco} secrets to {saifactory}.
.. From the main left panel, click menu:SUSE AI Factory[Settings].
.. In the `SUSE Application Collection` section, select the secrets name--that corresponds to the previously specified `<APPCO_SECRETS_NAME>`--from the `Secret name` drop-down lists.
.. Select `user` for menu:Username Secret[Secret Key] and `token` for menu:Access Token Secret[Secret Key].
.. Confirm with btn:[Apply] in the bottom right corner.
. Navigate to menu:SUSE AI Factory[Apps] and select btn:[SUSE AI Library] from the drop-down list in the top center of the screen.
. Click the btn:[Refresh] button in the top right.
The list of available applications from the {sappco} appears.

[#ai-factory-sregistry]
== How do I access images from {sregistry}?

. Enter {sregistry} secrets to the {ranchera} _local_ cluster.
.. From the main left panel, click menu:local[Storage > Secrets]
.. Click btn:[Create] in the top right and select btn:[Opaque]
.. Select the btn:[aif-operator] namespace and enter your preferred secrets name--see `<REGISTRY_SECRETS_NAME>` in the command-line example--to identify the secrets.
.. In the btn:[Data] tab, add key `user` with the value `regcode` and `token` for your {sregistry} token.
.. Confirm with btn:[Create] in the bottom right corner.

+
[TIP]
.Creating the secrets on the command line
====
[source,bash,subs="+attributes"]
----
{prompt_user}kubectl create secret generic <REGISTRY_SECRETS_NAME> \
  --from-literal=user=regcode \
  --from-literal=token=<REGISTRY_USER_TOKEN> \
  -n aif-operator
----
====
. Assign {sregistry} secrets to {saifactory}.
.. From the main left panel, click menu:SUSE AI Factory[Settings].
.. In the `SUSE Registry` section, select the secrets name--that corresponds to the previously specified `<REGISTRY_SECRETS_NAME>`--from the `Secret name` drop-down lists.
.. Select `user` for menu:Username Secret[Secret Key] and `token` for menu:Access Token Secret[Secret Key].
.. Confirm with btn:[Apply] in the bottom right corner.
. Navigate to menu:SUSE AI Factory[Apps] and select btn:[SUSE AI Library] from the drop-down list in the top center of the screen.
. Click the btn:[Refresh] button in the top right.
The list of available applications from the {sregistry} appears.

[#ai-factory-nvidia-registry]
== How do I access images from {nvidia} registry?

. Enter {nvidia} registry secrets to the {ranchera} _local_ cluster.
.. From the main left panel, click menu:local[Storage > Secrets]
.. Click btn:[Create] in the top right and select btn:[Opaque]
.. Select the btn:[aif-operator] namespace and enter your preferred secrets name--see `<NVIDIA_SECRETS_NAME>` in the command-line example--to identify the secrets.
.. In the btn:[Data] tab, add key `user` with the value `$oauthtoken` and `token` for your {nvidia} registry token.
.. Confirm with btn:[Create] in the bottom right corner.

+
[TIP]
.Creating {nvidia} secrets on the command line
====
[source,bash,subs="+attributes"]
----
{prompt_user}kubectl create secret generic <NVIDIA_SECRETS_NAME> \
  --from-literal=user=$oauthtoken \
  --from-literal=token=<NVIDIA_USER_TOKEN> \
  -n aif-operator
----
====
. Assign {nvidia} registry secrets to {saifactory}.
.. From the main left panel, click menu:SUSE AI Factory[Settings].
.. In the `NVIDIA` section, select the secrets name--that corresponds to the previously specified `<NVIDIA_SECRETS_NAME>`--from the `Secret name` drop-down lists.
.. Select `user` for menu:Username Secret[Secret Key] and `token` for menu:Access Token Secret[Secret Key].
.. Confirm with btn:[Apply] in the bottom right corner.
. Navigate to menu:SUSE AI Factory[Apps] and select btn:[NVIDIA Library] from the drop-down list in the top center of the screen.
. Click the btn:[Refresh] button in the top right.
The list of available applications from the {nvidia} registry appears.

[#ai-factory-fleet-gitops]
== How do I access a Git repository to store applications configuration?

. Enter Git Personal Access Token (PAT) to the {ranchera} _local_ cluster.
.. From the main left panel, click menu:local[Storage > Secrets]
.. Click btn:[Create] in the top right and select btn:[Opaque]
.. Select the btn:[aif-operator] namespace and enter your preferred secrets name--see `<GIT_SECRETS_NAME>` in the command-line example--to identify the secrets.
.. In the btn:[Data] tab, add the key `token` and paste your PAT as a value.
.. Confirm with btn:[Create] in the bottom right corner.

+
[TIP]
.Creating {nvidia} secrets on the command line
====
[source,bash,subs="+attributes"]
----
{prompt_user}kubectl create secret generic <GIT_SECRETS_NAME> \
  --from-literal=token=<NVIDIA_PAT_TOKEN> \
  -n aif-operator
----
====
. Add the Git PAT to {saifactory}.
.. From the main left panel, click menu:SUSE AI Factory[Settings].
.. In the `Fleet/GitOps` section, enter the Git repository URL and specify which branch to use.
.. Select authentication type and the PAT secrets name--that corresponds to the previously specified `<GIT_SECRETS_NAME>`--from the `Credential Secret` drop-down lists.
.. Select `token` for menu:Secret Key.
.. Confirm with btn:[Apply] in the bottom right corner.

[#ai-factory-airgapped]
== How do I access image registries in air-gapped environments?

In air-gapped environments, you must create a local offline repository for each image registry that you want to use to install applications.
Then, specify endpoints for these repositories.

. From the main left panel, click menu:SUSE AI Factory[Settings].
. In the menu:Advanced[Registry Endpoints] section, enter endpoint URLs for local {sappco}, {sregistry} or {nvidia} registry.
. Confirm with btn:[Apply] in the bottom right corner.