[#ai-factory-managing-apps]
include::../common/generic-attributes.adoc[]
// overridden title?
ifdef::override-title[]
= {override-title}
:revdate: 2026-01-26
:page-revdate: {revdate}
endif::[]
ifndef::override-title[]
= Managing AI applications using {productname}
endif::[]
// overridden abstract?
ifdef::override-abstract[]
{override-abstract}
endif::[]
ifndef::override-abstract[]
{productname} is a {ranchera} user interface extension and {kube} operator that helps you manage the entire lifecycle of AI applications and workloads.
It simplifies the deployment, configuration and scaling of AI workloads on {kube}, providing a streamlined experience for administering cluster-based artificial intelligence services.
endif::[]

// erase the flag for future overrides
:override-abstract!:
:override-title!:

[#ai-factory-apps-install]
== How do I install AI applications?

. From the main left panel, click menu:SUSE AI Factory[Apps].
ifeval::["{PROF_PRODUCT}" == "saif"]
. Select btn:[SUSE AI Library] and click the application's tile.
endif::[]
ifeval::["{PROF_PRODUCT}" == "saifnv"]
. Select btn:[NVIDIA Library] and click the application's tile.
endif::[]
You can also limit the number of displayed applications by entering a search string.
. The `Basic Information` screen of the installation wizard lets you update the application's instance name, namespace and version.
. On the `Target Cluster` screen, you can review hardware requirements for the workload, specify the deployment type, and which cluster to deploy the application to.
. The `Configuration` screen lets you change individual settings in the application's {helm} chart.
. The `Review` screen summarizes the basic information about the deployment.
Start the deployment by clicking the btn:[Install] button.
. After the installation progress bar reaches 100%, you can check the workload status by selecting menu:SUSE AI Factory[Workloads] from the left menu.


[#ai-factory-apps-manage]
== How do I manage application instances?

. From the main left panel, click menu:SUSE AI Factory[Workloads].
. Click the btn:[Manage] button pertaining to the application you want to manage.
. In the `Manage` wizard, you can update the application version, the cluster it belongs to, and its {helm} chart details.
. Confirm with btn:[Save].


[#ai-factory-apps-delete]
== How do I delete application instances?

. From the main left panel, click menu:SUSE AI Factory[Workloads].
. Click the btn:[Delete] button pertaining to the application you want to uninstall and confirm the deletion.