[#ai-lifecycle-manager-installing-applications]
include::../common/generic-attributes.adoc[]
// overridden title?
ifdef::override-title[]
= {override-title}
:revdate: 2026-01-26
:page-revdate: {revdate}
endif::[]
ifndef::override-title[]
= How to install and manage applications in {sailifecyclemanager}
endif::[]
// overridden abstract?
ifdef::override-abstract[]
{override-abstract}
endif::[]
ifndef::override-abstract[]
This guide explains how to use the {sailifecyclemanager} extension in {ranchera} to install, manage, and delete AI applications, covering the complete application lifecycle.
endif::[]

// erase the flag for future overrides
:override-abstract!:
:override-title!:

With the {sailifecyclemanager} extension, you can manage the full lifecycle of AI applications directly within {ranchera}. To install an application, you select it from the catalog and follow a wizard to configure and deploy it. To update or remove an application, you can navigate to its instance and use the manage or delete options.

[IMPORTANT]
====
Before you begin, ensure an administrator has installed the {sailifecyclemanager} extension and added the `ClusterRepos` repository. Only users with `Rancher Admin` and `Cluster Owner` roles can deploy and manage AI applications.
====

[#ai-lifecycle-manager-apps-installing]
[.procedure]
.How to install an application
. Click the application's tile to navigate to its instances page.
. Provide the basic information required for the {helm} installation, such as the release name, namespace and version.
  The repository is automatically selected.
  Click btn:[Next] to navigate to the `Target Cluster` page to select the cluster(s).
. On the `Target Cluster` page, choose one or more clusters that meet the application's resource requirements and click btn:[Next] to go to the `Configuration` page.
. On the `Configuration` page, customize the installation using the UI form for key settings or the YAML file for advanced options, and click btn:[Next] to go to the `Review` page.
. Review the installation summary on the `Review` page and confirm by clicking btn:[Install] to install the application.
  To navigate to previous steps to adjust the settings instead, click the btn:[Previous] button.

[#ai-lifecycle-manager-apps-managing]
[.procedure]
.How to manage an application instance
. Click the application's tile to navigate to its instances page.
. Click btn:[Manage] for the application to start its `Manage` wizard.
. Update the application's details on the wizard screens.
. On the `Review` page, click btn:[Save] to apply the changes.

[#ai-lifecycle-manager-apps-deleting]
[.procedure]
.How to delete an application instance
. Click the application's tile to navigate to its instances page.
. Click btn:[Delete] for the instance you want to delete.
. In the pop-up window, confirm the deletion.
