include::../common/generic-attributes.adoc[]
// overridden title?
ifdef::override-title[]
= {override-title}
endif::[]
ifndef::override-title[]
= Listing values list for {ai-app-name} {helm} chart
endif::[]
// overridden abstract?
ifdef::override-abstract[]
{override-abstract}
endif::[]
ifndef::override-abstract[]
Before deploying {ai-app-name}, it is important to know more about the supported configurations.
endif::[]

// erase the flag for future overrides
:override-abstract!:
:override-title!:

:revdate: 2026-09-14
:page-revdate: {revdate}

. (_Optional_) To get the values for a specific {ai-app-name} chart version, log in to {ai-app-registry} and identify the version.
To prevent the password from being stored in the shell history, save it to the `password.txt` file.
+
[,sh,subs="+attributes"]
----
ifeval::["{ai-app-registry}" == "{sregistry}"]
{prompt_user}skopeo login registry.suse.com \
  --username regcode \
  --password-stdin < password.txt
{prompt_user}skopeo list-tags docker://registry.suse.com/ai/charts/{ai-app-string}
endif::[]
ifeval::["{ai-app-registry}" == "{sappco}"]
{prompt_user}skopeo login dp.apps.rancher.io \
  --username <APPCO-USERNAME> \
  --password-stdin < password.txt
{prompt_user}skopeo list-tags docker://dp.apps.rancher.io/charts/{ai-app-string}
endif::[]
----

. Log in to {ai-app-registry} where {ai-app-name} chart is stored.
To prevent the password from being stored in the shell history, save it to the `password.txt` file.
+
[,sh,subs="+attributes"]
----
ifeval::["{ai-app-registry}" == "{sregistry}"]
{prompt_user}helm registry login registry.suse.com \
  --username regcode \
  --password-stdin < password.txt
endif::[]
ifeval::["{ai-app-registry}" == "{sappco}"]
{prompt_user}helm registry login dp.apps.rancher.io \
  --username <APPCO-USERNAME> \
  --password-stdin < appco-password.txt
endif::[]
----

. Display all values of the {ai-app-name} {helm} chart.
Omit `--version` to display the latest chart.
+
[,sh,subs="+attributes"]
----
ifeval::["{ai-app-registry}" == "{sregistry}"]
{prompt_user}helm show values oci://registry.suse.com/ai/charts/{ai-app-string} \
  --version <VERSION>
endif::[]
ifeval::["{ai-app-registry}" == "{sappco}"]
{prompt_user}helm show values oci://dp.apps.rancher.io/charts/{ai-app-string} \
  --version <VERSION>
endif::[]
----