include::../common/generic-attributes.adoc[]
// overridden title?
ifdef::override-title[]
= {override-title}
:revdate: 2026-08-03
:page-revdate: {revdate}
endif::[]
ifndef::override-title[]
= Providing registry credentials during {productname} installation
endif::[]
// overridden abstract?
ifdef::override-abstract[]
{override-abstract}
endif::[]
ifndef::override-abstract[]
ifeval::["{PROF_PRODUCT}" == "saif"]
To access applications and blueprints from {sappco} and {sregistry}, you need to provide valid credentials.
endif::[]
ifeval::["{PROF_PRODUCT}" == "saifnv"]
To access applications and blueprints from the {sappco}, {sregistry} and {nvidia} catalogs, you need to provide valid credentials.
endif::[]
By default, you can configure the credentials after the {productname} installation is complete as described in xref:ai-factory-post-deployment[].

However, you can specify the credentials during the {productname} installation process as well.
The result is identical--specifying credentials during the installation creates the secrets and configure the settings in {ranchera}.
endif::[]

// erase the flag for future overrides
:override-abstract!:
:override-title!:

[WARNING]
====
Storing credentials in a plain-text values YAML file poses a security risk.
Always restrict the file permissions of your override files to prevent unauthorized local access.
Avoid passing passwords directly in command-line arguments to prevent them from being recorded in your shell history.

For production environments, we recommend using secure secrets-management tools, such as the `helm-secrets` plug-in with Mozilla SOPS, or the External Secrets Operator.
====

[TIP]
====
User names for specific registries are preconfigured:

* {sregistry} uses `regcode`.
* {nvidia} catalog uses `$oauthtoken`.
====

[#aif-helm-credentials-procedure]
== Providing registry credentials during {helm} CLI installation

. Download and display the default values for the {productname} installation.
+
[source,bash,subs="+attributes"]
----
{prompt_user}helm show values oci://ghcr.io/suse/chart/aif-operator --version {aif-latest-version}
----

. Create the `aif-values.yaml` file and restrict its permissions so that only you can read and write to it:
+
[source,bash,subs="+attributes"]
----
{prompt_user}touch aif-values.yaml && chmod 600 aif-values.yaml
----

. Copy the section that deals with registry credentials into the file, for example:
+
[source,yaml]
----
credentials:
  # credential for oci://dp.apps.rancher.io/charts
  applicationCollection:
    username: ""
    password: ""
  # credential to pull NGC artifacts
  # e.g. https://helm.ngc.nvidia.com/nvidia
  nvidia:
    username: "$oauthtoken"
    password: ""
  # credential for oci://registry.suse.com/ai/charts
  suseRegistry:
    username: "regcode"
    password: ""
----

. Provide the credentials to individual registries in the related `username:` and `password:` fields.

. Save the file and install {productname} as described in xref:ai-factory-deployment-helm[] by specifying the override file, for example:
+
[source,bash,subs="+attributes"]
----
{prompt_user}helm install aif-operator \
  oci://ghcr.io/suse/chart/aif-operator:{aif-latest-version} \
  --namespace aif-operator \
  --create-namespace \
  -f aif-values.yaml
----


[#aif-rancher-credentials-procedure]
== Providing registry credentials during installation in {rancher}

include::../snippets/ai-rancher-admin-requirement.adoc[]

. Start the {productname} installation as described in xref:ai-factory-deployment-rancher-ui[].
. On the installation screen, activate btn:[Customize Helm options before install].
. Update the part of the installation chart that deals with registry credentials by providing credentials to individual registries.
+
[source,yaml]
----
credentials:
  # credential for oci://dp.apps.rancher.io/charts
  applicationCollection:
    username: ""
    password: ""
  # credential to pull NGC artifacts
  # e.g. https://helm.ngc.nvidia.com/nvidia
  nvidia:
    username: "$oauthtoken"
    password: ""
  # credential for oci://registry.suse.com/ai/charts
  suseRegistry:
    username: "regcode"
    password: ""
----

. Continue the installation by clicking the btn:[Install] button in the bottom right.