[#{ai-app-string}-installing]
include::../common/generic-attributes.adoc[]
// overridden title?
ifdef::override-title[]
= {override-title}
endif::[]
ifndef::override-title[]
= Installing {ai-app-name}
endif::[]
// overridden abstract?
ifdef::override-abstract[]
{override-abstract}
endif::[]
ifndef::override-abstract[]
You can install {ai-app-name} either using *{ranchera}* or on the command line with *{helm}*.
endif::[]

// erase the flag for future overrides
:override-abstract!:
:override-title!:

:revdate: 2026-09-14
:page-revdate: {revdate}

[#{ai-app-string}installing-rancher]
== Installing with {ranchera}

Refer to link:https://documentation.suse.com/suse-ai-factory/latest/html/AI-Factory-usage/ai-factory-managing-apps.html#ai-factory-apps-install[AI application installation] for a general installation procedure.

[#{ai-app-string}-installing-helm]
== Installing with {helm}

. Log in to {ai-app-registry}.
To prevent the password from being stored in the shell history, save it to the `password.txt` file.
+
[,sh,subs="+attributes"]
----
ifeval::["{ai-app-registry}" == "{sregistry}"]
{prompt_user}helm registry login registry.suse.com \
  --username=regcode \
endif::[]
ifeval::["{ai-app-registry}" == "{sappco}"]
{prompt_user}helm registry login dp.apps.rancher.io \
  --username=<APPCO-USERNAME> \
endif::[]
  --password-stdin < password.txt
----

. Create a namespace.
+
[,sh,subs="+attributes"]
----
{prompt_user}kubectl create namespace {ai-app-string}-system \
  --dry-run=client \
  -o yaml | kubectl apply -f -
----

. (_Optioonal_) If you have not created image pull secrets for {ai-app-registry}, create them now.
To prevent the password from being stored in the shell history, save it to the `password.txt` file.
+
[,sh,subs="+attributes"]
----
ifeval::["{ai-app-registry}" == "{sregistry}"]
{prompt_user}kubectl create secret docker-registry suse-ai-registry \
  --docker-server=registry.suse.com \
  --docker-username=regcode \
endif::[]
ifeval::["{ai-app-registry}" == "{sappco}"]
{prompt_user}kubectl create secret docker-registry application-collection \
  --docker-server=dp.apps.rancher.io \
  --docker-username=<APPCO-USERNAME> \
endif::[]
  --docker-password="$(< password.txt)" \
  -n {ai-app-string}-system \
  --dry-run=client -o yaml | kubectl apply -f -
----

. To override default installation values, list them in a `values.yaml` file.
For a complete list of {ai-app-name} chart values, refer to xref:{ai-app-string}-helm-values[].

. Install {ai-app-name}.
To keep the default installation values, omit `-f values.yaml`.
+
[,sh,subs="+attributes"]
----
{prompt_user}helm install {ai-app-string} \
ifeval::["{ai-app-registry}" == "{sregistry}"]
  oci://registry.suse.com/ai/charts/{ai-app-string} \
endif::[]
ifeval::["{ai-app-registry}" == "{sappco}"]
  oci://dp.apps.rancher.io/charts/{ai-app-string} \
endif::[]
  -n {ai-app-string}-system \
  -f values.yaml
----
