include::../common/generic-attributes.adoc[]
// overridden title?
ifdef::override-title[]
= {override-title}
endif::[]
ifndef::override-title[]
= Listing values list for {ai-app-name} {helm} chart
endif::[]
// overridden abstract?
ifdef::override-abstract[]
{override-abstract}
endif::[]
ifndef::override-abstract[]
To view the complete list of {helm} chart values for {ai-app-name}, follow these steps:
endif::[]

// erase the flag for future overrides
:override-abstract!:
:override-title!:

:revdate: 2026-09-14
:page-revdate: {revdate}

Before deploying {ai-app-name}, it is important to know more about the supported configurations.

. Log in to the registry where {ai-app-name} chart is stored.
To prevent the password from being stored in the shell history, save it to the `password.txt` file.
+
[,sh,subs="+attributes"]
----
{prompt_user}helm registry login registry.suse.com \
  --username regcode \
  --password-stdin < password.txt
----

. To view values for a specific version of {ai-app-name}, list all its available chart versions.
+
[,sh,subs="+attributes"]
----
{prompt_user}podman search --list-tags registry.suse.com/ai/charts/{ai-app-string}
----

. Display all values of {ai-app-name} {helm} chart.
Omit `--version` to display the latest chart.
+
[,sh,subs="+attributes"]
----
{prompt_user}helm show values oci://registry.suse.com/ai/charts/{ai-app-string} \
  --version <VERSION>
----