include::../common/generic-attributes.adoc[]
// overridden title?
ifdef::override-title[]
= {override-title}
:revdate: 2026-07-31
:page-revdate: {revdate}
endif::[]
ifndef::override-title[]
= Providing registry credentials during {productname} installation
endif::[]
// overridden abstract?
ifdef::override-abstract[]
{override-abstract}
endif::[]
ifndef::override-abstract[]
ifeval::["{PROF_PRODUCT}" == "saif"]
To access applications and blueprints from {sappco} and {sregistry}, you need to provide valid credentials.
endif::[]
ifeval::["{PROF_PRODUCT}" == "saifnv"]
To access applications and blueprints from {sappco}, {sregistry} and {nvidia} catalog, you need to provide valid credentials.
endif::[]
By default, you can configure the credentials after the {productname} installation is complete as described in xref:ai-factory-post-deployment[].

However, you can specify the credentials during the {productname} installation process as well.
endif::[]

// erase the flag for future overrides
:override-abstract!:
:override-title!:


[#aif-helm-credentials-procedure]
.Providing registry credentials during {helm} CLI installation

. Download and display the default values for the {productname} installation.
+
[source,bash,subs="+attributes"]
----
{prompt_user}helm show values oci://ghcr.io/suse/chart/aif-operator --version {aif-latest-version}
----

. Create a `aif-values.yaml` file and copy the part that deals with registry credentials, for example:
+
[source,yaml]
----
credentials:
  # credential for oci://dp.apps.rancher.io/charts
  applicationCollection:
    username: ""
    password: ""
  # credential to pull NGC artifacts
  # e.g. https://helm.ngc.nvidia.com/nvidia
  nvidia:
    username: ""
    password: ""
  # credential for oci://registry.suse.com/ai/charts
  suseRegistry:
    username: ""
    password: ""
----

. Provide the credentials to individual registries on the related `username:` and `password:` fields.

. Save the file and install {productname} as described in xref:ai-factory-deployment-helm[] by specifying the override file, for example:
+
[source,bash,subs="+attributes"]
----
{prompt_user}helm install aif-operator \
  oci://ghcr.io/suse/chart/aif-operator:{aif-latest-version} \
  --namespace aif-operator \
  --create-namespace \
  -f aif-values.yaml
----


include::../snippets/ai-rancher-admin-requirement.adoc[]

[#aif-rancher-credentials-procedure]
.Providing registry credentials during installation in {rancher}

. Start the {productname} installation as described in xref:ai-factory-deployment-rancher-ui[].
. On the installation screen, activate btn:[Customize Helm options before install].
. Update the part of the installation chart that deals with registry credentials by providing credentials to individual registries.
+
[source,yaml]
----
credentials:
  # credential for oci://dp.apps.rancher.io/charts
  applicationCollection:
    username: ""
    password: ""
  # credential to pull NGC artifacts
  # e.g. https://helm.ngc.nvidia.com/nvidia
  nvidia:
    username: ""
    password: ""
  # credential for oci://registry.suse.com/ai/charts
  suseRegistry:
    username: ""
    password: ""
----
. Continue the installation by clicking the btn:[Install] button in the bottom right.