include::../common/generic-attributes.adoc[]
// overridden title?
ifdef::override-title[]
= {override-title}
endif::[]
ifndef::override-title[]
= Installing {mcpo}
endif::[]
// overridden abstract?
ifdef::override-abstract[]
{override-abstract}
endif::[]
ifndef::override-abstract[]
{mcp} (Model Context Protocol) is an open source standard for connecting AI applications{mdash}such as {suseai}{mdash}to external systems.
These external systems can include data sources like databases or local files, or tools like calculators or search engines.

{mcpo} is the {mcp}-to-OpenAPI proxy server provided by {owui}.
It solves communication compatibility issues, enables cloud and UI integrations, and offers increased security and scalability.
endif::[]

// erase the flag for future overrides
:override-abstract!:
:override-title!:

:revdate: 2026-08-17
:page-revdate: {revdate}


ifeval::["{PROF_DEPLOYMENT}" == "standard"]
:imgRegistry: {empty}
endif::[]
ifeval::["{PROF_DEPLOYMENT}" == "airgapped"]
:imgRegistry: imageRegistry: <LOCAL_DOCKER_REGISTRY_URL>:5043
endif::[]

[#mcpo-owui-integration]
== Integrating {mcpo} with {owui}

To integrate {mcpo} with {owui}, follow these steps:
--
.Requirements
* {empty}
+
include::../snippets/openwebui-requirement-admin-privileges.adoc[]
--
. In the bottom left of the {owui} window, click your avatar icon to open the user menu and select btn:[Admin Panel].
. Click the btn:[Settings] tab and select btn:[Tools] from the left menu.
. Under btn:[Manage Tool Servers], click the `plus` icon to add a new connection.
. For each {mcp} server:
** Provide the server URL, name and description.
** Set the visibility to btn:[Public] to make it available to all users.
** Check if the connection is successful and confirm with btn:[Save].
+
[TIP]
====
The general URL format is: MCPO_URL/MCP_SERVER_NAME.
For example, if {mcpo} was deployed as `mcpo` in the namespace `suse-ai` with the default port configuration, the URL is:
[source,subs="+attributes"]
----
http://mcpo-open-webui-mcpo.suse-ai.svc.cluster.local:8000/MCP_SERVER_NAME
----
====

After you have configured at least one {mcp} server, you can enable them from the {owui} chat input field to make answers more specific.
For more information, see link:https://documentation.suse.com/suse-ai/1.0/html/openwebui-using/index.html#openwebui-input-field-specify-mcpo-tools[Selecting {mcpo} services from the chat input field].

[TIP]
.Enabling {mcp} tools by default
====
To enable selected {mcp} tools by default for a model, refer to link:https://documentation.suse.com/suse-ai/1.0/html/openwebui-configuring/index.html#owui-enabling-default-mcp-services[Enabling default {mcp} services].
====