[#opensearch-installing]
= Installing {opensearch}
:revdate: 2026-03-24
:page-revdate: {revdate}

ifeval::["{PROF_DEPLOYMENT}" == "standard"]
:imgRegistry: {empty}
endif::[]
ifeval::["{PROF_DEPLOYMENT}" == "airgapped"]
:imgRegistry: imageRegistry: <LOCAL_DOCKER_REGISTRY_URL>:5043
endif::[]

{opensearch} is a community-driven, open source search and analytics suite.
It is used to search, visualize and analyze data.
{opensearch} consists of a data store and search engine ({opensearch}), a visualization and user interface ({opensearch} Dashboards), and a server-side data collector (Data Prepper).
Its functionality can be extended by plug-ins that enhance features like search, analytics, observability, security or machine learning.

[#opensearch-installing-app-details]
== Details about the {opensearch} application

Before deploying {opensearch}, it is important to know more about the supported configurations and documentation.
The following command provides the corresponding details:

[source,bash,subs="+attributes"]
----
{prompt_user}helm show values oci://dp.apps.rancher.io/charts/opensearch
----

Alternatively, you can also refer to the {opensearch} {helm} chart page on the {sappco} site at link:https://apps.rancher.io/applications/opensearch[].
It contains {opensearch} dependencies, available versions and the link to pull the {opensearch} container image.

ifeval::["{PROF_DEPLOYMENT}" == "standard"]
[#opensearch-upgrading]
== Upgrading {opensearch}

The {opensearch} chart receives application updates and updates of the {helm} chart templates.
New versions may include changes that require manual steps.
These steps are listed in the corresponding `README` file.
All {opensearch} dependencies are updated automatically during an {opensearch} upgrade.

To upgrade {opensearch}, identify the new version number and run the following command below:

[source,bash,subs="+attributes"]
----
{prompt_user}helm upgrade --install \
  opensearch oci://dp.apps.rancher.io/charts/opensearch \
  -n <SUSE_AI_NAMESPACE> \
  --version <VERSION_NUMBER> \
  -f <opensearch_custom_overrides.yaml>
----

[TIP]
====
If you omit the `--version` option, {opensearch} gets upgraded to the latest available version.
====
endif::[]

[#opensearch-uninstalling]
== Uninstalling {opensearch}

To uninstall {opensearch}, run the following command:

[source,bash,subs="+attributes"]
----
{prompt_user}helm uninstall opensearch -n <SUSE_AI_NAMESPACE>
----
