include::../common/generic-attributes.adoc[]
// overridden title?
ifdef::override-title[]
= {override-title}
endif::[]
ifndef::override-title[]
= Installing {qdrant}
endif::[]
// overridden abstract?
ifdef::override-abstract[]
{override-abstract}
endif::[]
ifndef::override-abstract[]
{qdrant} is an AI-native vector database and a semantic search engine. 
You can use it to extract meaningful information from unstructured data.
endif::[]

// erase the flag for future overrides
:override-abstract!:
:override-title!:

:revdate: 2026-08-17
:page-revdate: {revdate}

[#qdrant-owui-integration]
== Integrating {qdrant} with {owui}

To integrate {qdrant} with {owui}, follow these steps:

. Edit the override file for {owui}, `owui_custom_overrides.yaml` and update the `extraEnvVars` section as follows.
+
* Change the `VECTOR_DB` value to `qdrant`.
* Add the {qdrant}-related environment variables: 
+
[source,yaml]
----
extraEnvVars:
- name: DEFAULT_MODELS
  value: "gemma:2b"
- name: DEFAULT_USER_ROLE
  value: "pending"
- name: ENABLE_SIGNUP
  value: "true"
- name: GLOBAL_LOG_LEVEL
  value: INFO
- name: RAG_EMBEDDING_MODEL
  value: "sentence-transformers/all-MiniLM-L6-v2"
- name: INSTALL_NLTK_DATASETS
  value: "true"
- name: VECTOR_DB
  value: "qdrant"
- name: QDRANT_URI
  value: http://qdrant.<SUSE_AI_NAMESPACE>.svc.cluster.local:6333
# Optional: If your Qdrant instance requires authentication, provide the API key here
#- name: QDRANT_API_KEY
#  value: <qdrant_api_key>
- name: OPENAI_API_KEY
  value: "0p3n-w3bu!"
----
. Redeploy {owui}.
+
ifeval::["{PROF_DEPLOYMENT}" == "standard"]
[source,bash,subs="+attributes"]
----
{prompt_user}helm upgrade --install \
  open-webui oci://dp.apps.rancher.io/charts/open-webui \
  -n <SUSE_AI_NAMESPACE> \
  -f <owui_custom_overrides.yaml>
----
endif::[]
ifeval::["{PROF_DEPLOYMENT}" == "airgapped"]
[source,bash,subs="+attributes"]
----
{prompt_user}helm upgrade --install \
  open-webui charts/open-webui-<X.Y.Z>.tgz \
  -n <SUSE_AI_NAMESPACE> \
  --version <X.Y.Z> \
  -f <owui_custom_overrides.yaml>
----
endif::[]
. Verify that `VECTOR_DB` is set to `qdrant`.
+
[source,bash,subs="+attributes"]
----
{prompt_user}kubectl exec -it open-webui-0 -n <SUSE_AI_NAMESPACE> \
  -- sh -c 'echo "VECTOR_DB=$VECTOR_DB"'

Defaulted container "open-webui" out of: open-webui, copy-app-data (init)
VECTOR_DB=qdrant
----