include::../common/generic-attributes.adoc[]
// overridden title?
ifdef::override-title[]
= {override-title}
endif::[]
ifndef::override-title[]
= Appendix
endif::[]
// overridden abstract?
ifdef::override-abstract[]
{override-abstract}
endif::[]
ifndef::override-abstract[]
{empty}
endif::[]

// erase the flag for future overrides
:override-abstract!:
:override-title!:

:revdate: 2026-07-03
:page-revdate: {revdate}

== Product Support Lifecycle

{productname} is backed by award-winning support from {suse}, an established technology leader with a proven history of delivering enterprise-quality support services.
For more information, see https://www.suse.com/lifecycle[Lifecycle Dates by Product] and https://www.suse.com/support/policy.html[Support Policy] pages.
If you have any questions about raising a support case, how {suse} classifies severity levels, or the scope of support, see the at https://www.suse.com/support/handbook/[Technical Support Handbook].

{productname} is supported for 18-months of production support, with an initial 6-months of "full support," followed by 12-months of "maintenance support."
After these support phases, the product reaches "end of life" (EOL) and is no longer supported.
More information about the lifecycle phases can be found in the table below:

|======
| *Full Support (6 months)* | Urgent and selected high-priority bug fixes will be released during the full support window, and all other patches (non-urgent, enhancements, new capabilities) will be released via the regular release schedule.
| *Maintenance Support (12 months)* | During this period, only critical fixes will be released via patches. Other bug fixes may be released at {suse}'s discretion but should not be expected.
| *End of Life (EOL)*  | Once a product release reaches its End of Life date, the customer may continue to use the product within the terms of product licensing agreement.
Support Plans from {suse} do not apply to product releases past their EOL date.
|======

Unless explicitly stated, all components listed are considered Generally Available (GA), and are covered by {suse}'s standard scope of support. Certain components may be listed as "Technology Preview," where {suse} is providing customers with access to early pre-GA features and functionality for evaluation, but are not subject to the standard support policies and are not recommended for production use cases.
{suse} welcomes feedback and suggestions on the improvements that can be made to Technology Preview components, but {suse} reserves the right to deprecate a Technology Preview feature before it becomes Generally Available if it does not meet the needs of our customers or does not reach a state of maturity that we require.

{suse} must occasionally deprecate features or change API specifications.
Reasons for feature deprecation or API change could include a feature being updated or replaced by a new implementation, a new feature set, upstream technology is no longer available, or the upstream community has introduced incompatible changes.
It is not intended that this will ever happen within a given minor release (x.z), and so all z-stream releases will maintain API compatibility and feature functionality.
{suse} will endeavor to provide deprecation warnings with plenty of notice within the release notes, along with workarounds, suggestions and mitigations to minimize service disruption.

== Obtaining source code

This {suse} product includes materials licensed to {suse} under the GNU General Public License (GPL) and various other open source licenses.
The GPL requires {suse} to provide the source code that corresponds to the GPL-licensed material, and {suse} conforms to all other open-source license requirements.
As such, {suse} makes all source code available, and can generally be found in the link:https://github.com/{suse}/aif[{saifactory} GitHub repository] and the link:https://www.github.com/rancher[{suse} {ranchera} GitHub repository] for dependent components.

== Legal notices

{suse} makes no representations or warranties with regard to the contents or use of this documentation, and specifically disclaims any express or implied warranties of merchantability or fitness for any particular purpose. Further, {suse} reserves the right to revise this publication and to make changes to its content, at any time, without the obligation to notify any person or entity of such revisions or changes.

Further, {suse} makes no representations or warranties with regard to any software, and specifically disclaims any express or implied warranties of merchantability or fitness for any particular purpose. Further, {suse} reserves the right to make changes to any and all parts of {suse} software, at any time, without any obligation to notify any person or entity of such changes.

Any products or technical information provided under this Agreement may be subject to U.S. export controls and the trade laws of other countries. You agree to comply with all export control regulations and to obtain any required licenses or classifications to export, re-export, or import deliverables. You agree not to export or re-export to entities on the current U.S. export exclusion lists or to any embargoed or terrorist countries as specified in U.S. export laws. You agree to not use deliverables for prohibited nuclear, missile, or chemical/biological weaponry end uses. Refer to https://www.suse.com/company/legal/[https://www.suse.com/company/legal/] for more information on exporting {suse} software. {suse} assumes no responsibility for your failure to obtain any necessary export approvals.

*Copyright © 2024 {suse} LLC.*

This release notes document is licensed under a Creative Commons Attribution-NoDerivatives 4.0 International License (CC-BY-ND-4.0). You should have received a copy of the license along with this document. If not, see https://creativecommons.org/licenses/by-nd/4.0/[https://creativecommons.org/licenses/by-nd/4.0/].

{suse} has intellectual property rights relating to technology embodied in the product that is described in this document. In particular, and without limitation, these intellectual property rights may include one or more of the U.S. patents listed at https://www.suse.com/company/legal/[https://www.suse.com/company/legal/] and one or more additional patents or pending patent applications in the U.S. and other countries.

For {suse} trademarks, see the {suse} Trademark and Service Mark list (https://www.suse.com/company/legal/[https://www.suse.com/company/legal/]). All third-party trademarks are the property of their respective owners. For {suse} brand information and usage requirements, please see the guidelines published at https://brand.suse.com/[https://brand.suse.com/].