include::../common/generic-attributes.adoc[]
// overridden title?
ifdef::override-title[]
= {override-title}
endif::[]
ifndef::override-title[]
= {milvus}
endif::[]
// overridden abstract?
ifdef::override-abstract[]
{override-abstract}
endif::[]
ifndef::override-abstract[]
{milvus} is a scalable, high-performance vector database designed for AI applications.
It enables efficient organization and searching of massive unstructured datasets, including text, images and multi-modal content.
endif::[]

// erase the flag for future overrides
:override-abstract!:
:override-title!:

:revdate: 2026-08-06
:page-revdate: {revdate}

include::../snippets/helm-chart-overrides-intro.adoc[]

ifeval::["{PROF_DEPLOYMENT}" == "standard"]
:imgRegistry: {empty}
endif::[]
ifeval::["{PROF_DEPLOYMENT}" == "airgapped"]
:imgRegistry: imageRegistry: <LOCAL_DOCKER_REGISTRY_URL>:5043
endif::[]

include::../snippets/ai-library-requirement.adoc[]

. When installed as part of {productname}, {milvus} depends on {etcd}, {minio} and {akafka}.
Because the {milvus} chart uses a non-default configuration, create an override file `milvus_custom_overrides.yaml` with the following content.
+
ifeval::["{PROF_DEPLOYMENT}" == "standard"]
[TIP]
====
As a template, you can download the {milvus} {helm} chart that includes the `values.yaml` file with the default configuration by running the following command:

[source,bash,subs="+attributes"]
----
{prompt_user}helm pull oci://dp.apps.rancher.io/charts/milvus --version 4.2.2
----
====
endif::[]
ifeval::["{PROF_DEPLOYMENT}" == "airgapped"]
[TIP]
====
As a template, you can use the `values.yaml` file that is included in the `charts/milvus-<X.Y.Z>.tgz` TAR archive.
====
endif::[]
+
[source,yaml,subs="+attributes"]
----
global:
  imagePullSecrets:
  - application-collection
  {imgRegistry}
cluster:
  enabled: true
standalone:
  persistence:
    persistentVolumeClaim:
      storageClassName: "local-path"
etcd:
  replicaCount: 1
  persistence:
    storageClassName: "local-path"
minio:
  mode: distributed
  replicas: 4
  rootUser: "admin"
  rootPassword: "adminminio"
  persistence:
    storageClass: "local-path"
  resources:
    requests:
      memory: 1024Mi
kafka:
  enabled: true
  name: kafka
  replicaCount: 3
  broker:
    enabled: true
  cluster:
    listeners:
      client:
        protocol: 'PLAINTEXT'
      controller:
        protocol: 'PLAINTEXT'
  persistence:
    enabled: true
    annotations: {}
    labels: {}
    existingClaim: ""
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 8Gi
    storageClassName: "local-path"
extraConfigFiles: <.>
  user.yaml: |+
    trace:
      exporter: jaeger
      sampleFraction: 1
      jaeger:
        url: "http://opentelemetry-collector.observability.svc.cluster.local:14268/api/traces" <.>
----
<.> The `extraConfigFiles` section is optional, required only to receive telemetry data from {owui}.
<.> The URL of the {otelemetry} Collector installed by the user.
+
[TIP]
====
The above example uses local storage.
For production environments, we recommend using an enterprise class storage solution such as {sstorage} in which case the `storageClassName` option must be set to `longhorn`.
====
. Install the {milvus} {helm} chart using the `milvus_custom_overrides.yaml` override file.
+
ifeval::["{PROF_DEPLOYMENT}" == "standard"]
[source,bash,subs="+attributes"]
----
{prompt_user}helm upgrade --install \
  milvus oci://dp.apps.rancher.io/charts/milvus \
  -n <SUSE_AI_NAMESPACE> \
  --version 4.2.2 -f <milvus_custom_overrides.yaml>
----
endif::[]
ifeval::["{PROF_DEPLOYMENT}" == "airgapped"]
[source,bash,subs="+attributes"]
----
{prompt_user}helm upgrade --install \
  milvus charts/milvus-<X.Y.Z>.tgz \
  -n <SUSE_AI_NAMESPACE> \
  --version <X.Y.Z> \
  -f <milvus_custom_overrides.yaml>
----
endif::[]

[#milvus-kafka-limitation]
== Using {akafka} with {sstorage}

When {milvus} is deployed in cluster mode, it uses {akafka} as a message queue.
If {akafka} uses {sstorage} as a storage back-end, you need to create an XFS storage class and make it available for the {akafka} deployment.
Otherwise deploying {akafka} with a storage class of an Ext4 file system fails with the following error:

[source]
----
"Found directory /mnt/kafka/logs/lost+found, 'lost+found' is not
  in the form of topic-partition or topic-partition.uniqueId-delete
  (if marked for deletion)"
----

To introduce the XFS storage class, follow these steps:

. Create a file named `longhorn-xfs.yaml` with the following content:
+
[source,yaml]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-xfs
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  fromBackup: ""
  fsType: "xfs"
  dataLocality: "disabled"
  unmapMarkSnapChainRemoved: "ignored"
----
. Create the new storage class using the `kubectl` command.
+
[source,bash,subs="+attributes"]
----
{prompt_user}kubectl apply -f longhorn-xfs.yaml
----
. Update the {milvus} overrides YAML file to reference the {akafka} storage class, as in the following example:
+
[source,yaml]
----
  [...]
    kafka:
    enabled: true
    persistence:
      storageClassName: longhorn-xfs
----