include::../common/generic-attributes.adoc[]
// overridden title?
ifdef::override-title[]
= {override-title}
endif::[]
ifndef::override-title[]
= {milvus}
endif::[]
// overridden abstract?
ifdef::override-abstract[]
{override-abstract}
endif::[]
ifndef::override-abstract[]
include::../snippets/helm-chart-overrides-intro.adoc[]
endif::[]

// erase the flag for future overrides
:override-abstract!:
:override-title!:

:revdate: 2026-09-16
:page-revdate: {revdate}

[#milvus-kafka-limitation]
== Using {akafka} with {sstorage}

When {milvus} is deployed in cluster mode, it uses {akafka} as a message queue.
If {akafka} uses {sstorage} as a storage back-end, you need to create an XFS storage class and make it available for the {akafka} deployment.
Otherwise deploying {akafka} with a storage class of an Ext4 file system fails with the following error:

[source]
----
"Found directory /mnt/kafka/logs/lost+found, 'lost+found' is not
  in the form of topic-partition or topic-partition.uniqueId-delete
  (if marked for deletion)"
----

To introduce the XFS storage class, follow these steps:

. Create a file named `longhorn-xfs.yaml` with the following content:
+
[source,yaml]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-xfs
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  fromBackup: ""
  fsType: "xfs"
  dataLocality: "disabled"
  unmapMarkSnapChainRemoved: "ignored"
----
. Create the new storage class using the `kubectl` command.
+
[source,bash,subs="+attributes"]
----
{prompt_user}kubectl apply -f longhorn-xfs.yaml
----
. Update the custom values file for {milvus} to reference the {akafka} storage class, as in the following example:
+
[source,yaml]
----
  [...]
    kafka:
    enabled: true
    persistence:
      storageClassName: longhorn-xfs
----